/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/logs": {
    get: operations["listLogs"];
    put: operations["putLog"];
    post: operations["createLog"];
  };
  "/logs/{date}": {
    get: operations["showLogByDate"];
    delete: operations["deleteLogByDate"];
  };
}

export interface components {
  schemas: {
    /** @example [object Object] */
    Log: {
      date: string;
      /** Format: int32 */
      foo: number;
      bar?: boolean;
    } & {
      hoge: unknown;
    };
    /** @example [object Object],[object Object] */
    Logs: components["schemas"]["Log"][];
    /** @example [object Object] */
    Error: {
      /** Format: int32 */
      code?: number;
      message: string;
    } & {
      status: unknown;
    };
  };
}

export interface operations {
  listLogs: {
    responses: {
      /** Array of logs */
      200: {
        content: {
          "application/json": components["schemas"]["Logs"];
        };
      };
      /** unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  putLog: {
    responses: {
      /** Update results */
      200: {
        content: {
          "application/json": components["schemas"]["Log"];
        };
      };
      /** unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** log to update */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Log"];
      };
    };
  };
  createLog: {
    responses: {
      /** Null response */
      201: unknown;
      /** unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** log to create */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Log"];
      };
    };
  };
  showLogByDate: {
    parameters: {
      path: {
        /** The date string formatted yyyy/MM/dd */
        date: string;
      };
    };
    responses: {
      /** Expected response to a valid request */
      200: {
        content: {
          "application/json": components["schemas"]["Log"];
        };
      };
      /** unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  deleteLogByDate: {
    parameters: {
      path: {
        /** The date string formatted yyyy/MM/dd */
        date: string;
      };
    };
    responses: {
      /** Expected response to a valid request */
      204: never;
      /** unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}

export interface external {}
